version: "1.0"
info:
  model: int-scaffold
packages:
- name: TempAccProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.tempacc.integrations:test
  packages:
  - name: TempAccProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.1986
